server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git: 
                  default-label: config-server
                  uri: https://github.com/Pablo-mandalorian/micro-services.git
                  search-paths: config-data
    application:
        name: config-server
        
